---
title: "Assignment 1"
---

## Assignment 1 - ilhan emre can

```{r}
library(dslabs)

my_first <- "ilhan"
my_birth_year <- 2002
k <- (nchar(my_first) + my_birth_year) %% 15 + 8
k
```

```{r}
data("polls_us_election_2016")
polls <- polls_us_election_2016
head(polls)
```

```{r}
total_na <- sum(is.na(polls))
total_na
```

```{r}
na_per_column <- colSums(is.na(polls))
na_sorted <- sort(na_per_column, decreasing = TRUE)
top_8_na <- head(na_sorted, 8)
top_8_na
```

**help of ai**

```{r}
new_data <- polls

numeric_value <- my_birth_year + k
text_value <- paste0(my_first, "_", k)

for(col in names(new_data)){
  if(is.numeric(new_data[[col]])){
    new_data[[col]][is.na(new_data[[col]])] <- numeric_value
  }
}

for(col in names(new_data)){
  if(is.character(new_data[[col]])){
    new_data[[col]][is.na(new_data[[col]])] <- text_value
  }
  if(is.factor(new_data[[col]])){
    new_data[[col]] <- as.character(new_data[[col]])
    new_data[[col]][is.na(new_data[[col]])] <- text_value
  }
}
```

```{r}
if(k %% 2 == 0){
  result_new <- head(new_data, k)
} else {
  result_new <- tail(new_data, k)
}

result_new
```

**ai help ends**

```{r}
sum(is.na(new_data))
anyNA(new_data)
```
